# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID ', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=50)),
                ('female', models.BooleanField(default=False)),
                ('SSN', models.CharField(max_length=9)),
                ('age', models.IntegerField(help_text='age')),
                ('snf', models.CharField(help_text='snf', max_length=3)),
                ('nephrologist', models.CharField(max_length=3)),
                ('chf', models.CharField(help_text='CHF', max_length=3)),
                ('sob', models.CharField(help_text='sob', max_length=3)),
                ('cancer', models.CharField(help_text='cancer', max_length=3)),
                ('weight_loss', models.CharField(default='no', help_text='cancer', max_length=3)),
                ('appetite', models.CharField(default='no', help_text='appetite', max_length=3)),
                ('memory', models.CharField(default='no', help_text='memory', max_length=3)),
                ('mobility', models.CharField(default='no', help_text='mobility', max_length=3)),
                ('eating', models.CharField(default='no', help_text='eating', max_length=3)),
                ('toileting', models.CharField(default='no', help_text='toileting', max_length=3)),
                ('hygiene', models.CharField(default='no', help_text='personal hygiene', max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
