# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 22:16
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=50)),
                ('female', models.BooleanField(default=False)),
                ('SSN', models.CharField(max_length=9)),
                ('age', models.IntegerField(help_text='age')),
                ('snf', models.CharField(blank=True, help_text='snf', max_length=3)),
                ('nephrologist', models.CharField(blank=True, help_text='nephrology', max_length=3)),
                ('chf', models.CharField(blank=True, help_text='CHF', max_length=3)),
                ('sob', models.CharField(blank=True, help_text='sob', max_length=3)),
                ('cancer', models.CharField(blank=True, help_text='cancer', max_length=3)),
                ('weight_loss', models.CharField(blank=True, default='no', help_text='cancer', max_length=3)),
                ('appetite', models.CharField(blank=True, default='no', help_text='appetite', max_length=3)),
                ('memory', models.CharField(blank=True, default='no', help_text='memory', max_length=3)),
                ('mobility', models.CharField(blank=True, default='no', help_text='mobility', max_length=3)),
                ('eating', models.CharField(blank=True, default='no', help_text='eating', max_length=3)),
                ('toileting', models.CharField(blank=True, default='no', help_text='toileting', max_length=3)),
                ('hygiene', models.CharField(blank=True, default='no', help_text='personal hygiene', max_length=3)),
                ('rai', models.IntegerField(default=0, help_text='RAI')),
                ('created_by', models.CharField(default='1', max_length=20, null=True, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
    ]
