# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appetite',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cancer',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chf',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eating',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hygiene',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobility',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nephrologist',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='snf',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='toileting',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight_loss',
        ),
    ]
