# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0002_auto_20171129_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='snf',
            field=models.CharField(blank=True, help_text='snf', max_length=3),
        ),
    ]
