# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0003_patient_snf'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chf',
            field=models.CharField(blank=True, help_text='CHF', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='nephrologist',
            field=models.CharField(blank=True, help_text='nephrology', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='sob',
            field=models.CharField(blank=True, help_text='sob', max_length=3),
        ),
    ]
