# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LariatApp', '0004_auto_20171129_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appetite',
            field=models.CharField(blank=True, default='no', help_text='appetite', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='cancer',
            field=models.CharField(blank=True, help_text='cancer', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='eating',
            field=models.CharField(blank=True, default='no', help_text='eating', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='hygiene',
            field=models.CharField(blank=True, default='no', help_text='personal hygiene', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='memory',
            field=models.CharField(blank=True, default='no', help_text='memory', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobility',
            field=models.CharField(blank=True, default='no', help_text='mobility', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='toileting',
            field=models.CharField(blank=True, default='no', help_text='toileting', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_loss',
            field=models.CharField(blank=True, default='no', help_text='cancer', max_length=3),
        ),
    ]
