# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0005_auto_20171130_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eating',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hygiene',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobility',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='toileting',
        ),
    ]
