# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0006_auto_20171130_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='eating',
            field=models.CharField(blank=True, default='no', help_text='eating', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='hygiene',
            field=models.CharField(blank=True, default='no', help_text='personal hygiene', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='memory',
            field=models.CharField(blank=True, default='no', help_text='memory', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobility',
            field=models.CharField(blank=True, default='no', help_text='mobility', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='toileting',
            field=models.CharField(blank=True, default='no', help_text='toileting', max_length=3),
        ),
    ]
