# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0009_patient_mobility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mobility',
        ),
    ]
