# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0011_patient_mobility'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='eating',
            field=models.CharField(blank=True, default='no', help_text='eating', max_length=3),
        ),
    ]
