# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0012_patient_eating'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hygiene',
            field=models.CharField(blank=True, default='no', help_text='personal hygiene', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='toileting',
            field=models.CharField(blank=True, default='no', help_text='toileting', max_length=3),
        ),
    ]
