# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0013_auto_20171130_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rai',
            field=models.IntegerField(default=0, help_text='RAI'),
        ),
    ]
