# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0015_remove_patient_rai'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rai',
            field=models.IntegerField(default=0, help_text='RAI'),
        ),
    ]
