# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LariatApp', '0020_patient_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
    ]
